CREATE TABLE Usuario
(USU_ID				INT PRIMARY KEY IDENTITY(1,1) NOT NULL
,RED_ID				INT REFERENCES Rede (RED_ID) NOT NULL
,CAR_ID				INT REFERENCES Cargo (CAR_ID) NOT NULL
,CAT_ID				INT REFERENCES Categoria (CAT_ID) NOT NULL
,USU_NOME			VARCHAR(128) NOT NULL
,USU_EMAIL			VARCHAR(128) NULL
,USU_SENHA			VARCHAR(32) NOT NULL
,USU_BIOGRAFIA		VARCHAR(256) NULL
,USU_FOTO			VARCHAR(128) NULL
,USU_DH_CADASTRO	DATETIME DEFAULT(getDate())
,USU_ATIVO			BIT NOT NULL DEFAULT(1)
)
GO
CREATE TABLE UsuarioPrivacidade
(PRI_ID			INT PRIMARY KEY IDENTITY(1,1) NOT NULL
,USU_ID			INT REFERENCES Usuario (USU_ID) NOT NULL
,PRI_PERFIL		BIT NOT NULL DEFAULT(0)
,PRI_FOTOS		BIT NOT NULL DEFAULT(0)
,PRI_VIDEOS		BIT NOT NULL DEFAULT(0)
)
GO
CREATE TABLE UsuarioNotificacao
(NOT_ID				INT PRIMARY KEY IDENTITY(1,1) NOT NULL
,USU_ID				INT REFERENCES Usuario (USU_ID) NOT NULL
,NOT_BLOG			BIT NOT NULL DEFAULT(0)
,NOT_GALERIA		BIT NOT NULL DEFAULT(0)
,NOT_FORUM			BIT NOT NULL DEFAULT(0)
,NOT_DOCUMENTADAS	BIT NOT NULL DEFAULT(0)
)
GO
CREATE TABLE UsuarioFotos
(FOT_ID				INT PRIMARY KEY IDENTITY(1,1) NOT NULL
,USU_ID				INT REFERENCES Usuario (USU_ID) NOT NULL
,FOT_IMAGEM			VARCHAR(128) NOT NULL
,FOT_LEGENDA		VARCHAR(64) NULL
,FOT_DH_PUBLICACAO	DATETIME DEFAULT(getDate())
,FOT_ATIVO			BIT NOT NULL DEFAULT(1)
)

GO
CREATE TABLE UsuarioVideos
(VID_ID				INT PRIMARY KEY IDENTITY(1,1) NOT NULL
,USU_ID				INT REFERENCES Usuario (USU_ID) NOT NULL
,VID_TITULO			VARCHAR(128) NOT NULL
,VID_LINK			VARCHAR(64) NOT NULL
,VID_DH_PUBLICACAO	DATETIME DEFAULT(getDate())
,VID_ATIVO			BIT NOT NULL DEFAULT(1)
)
GO
CREATE TABLE UsuarioPost
(POS_ID				INT PRIMARY KEY IDENTITY(1,1) NOT NULL
,USU_ID				INT REFERENCES Usuario (USU_ID) NOT NULL
,POS_TITULO			VARCHAR(128) NOT NULL
,POS_IMAGEM			VARCHAR(64) NULL
,POS_TEXTO			TEXT NOT NULL
,POS_DH_PUBLICACAO	DATETIME DEFAULT(getDate())
,POS_ATIVO			BIT NOT NULL DEFAULT(1)
)